name: jarvis-phase-4-content-generation
description: Build autonomous content generation. AI-powered flashcard generation, essay draft creation, study guide generation, and Canvas integration enhancement.
author: BMad Builder
config_source: '{project-root}/bmad/jarvis/config.yaml'
output_folder: '{config_source}:output_folder'
user_name: '{config_source}:user_name'
communication_language: '{config_source}:communication_language'
date: system-generated
installed_path: '{project-root}/bmad/jarvis/workflows/jarvis-phase-4-content-generation'
instructions: '{installed_path}/instructions.md'
validation: '{installed_path}/checklist.md'
standalone: true
template: false
phase: 4
duration_weeks: 8
default_output_file: '{output_folder}/JARVIS_PHASE4_BUILD_LOG.md'
