using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Asp.Versioning;
using FocusDeck.Domain.Entities.Automations;
using FocusDeck.Persistence;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FocusDeck.Server.Controllers.v1.Jarvis
{
    [ApiController]
    [ApiVersion("1.0")]
    [Route("v{version:apiVersion}/automations/proposals")]
    [Authorize]
    public class AutomationProposalsController : ControllerBase
    {
        private readonly AutomationDbContext _dbContext;

        public AutomationProposalsController(AutomationDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        /// <summary>
        /// Retrieves a list of pending automation proposals generated by Jarvis.
        /// </summary>
        [HttpGet]
        public async Task<ActionResult<List<AutomationProposalDto>>> GetProposals(CancellationToken cancellationToken)
        {
            var proposals = await _dbContext.AutomationProposals
                .AsNoTracking()
                .Where(p => p.Status == ProposalStatus.Pending)
                .OrderByDescending(p => p.CreatedAt)
                .Select(p => new AutomationProposalDto(
                    p.Id,
                    p.Title,
                    p.Description,
                    p.YamlDefinition,
                    p.ConfidenceScore))
                .ToListAsync(cancellationToken);

            return Ok(proposals);
        }
    }

    public record AutomationProposalDto(
        System.Guid Id,
        string Title,
        string Description,
        string YamlDefinition,
        float ConfidenceScore
    );
}
