name: jarvis-phase-2-burnout-detection
description: Build burnout detection and prevention system. Pattern recognition, wellness metrics tracking, smart break enforcement, and burnout alert notifications.
author: BMad Builder
config_source: '{project-root}/bmad/jarvis/config.yaml'
output_folder: '{config_source}:output_folder'
user_name: '{config_source}:user_name'
communication_language: '{config_source}:communication_language'
date: system-generated
installed_path: '{project-root}/bmad/jarvis/workflows/jarvis-phase-2-burnout-detection'
instructions: '{installed_path}/instructions.md'
validation: '{installed_path}/checklist.md'
standalone: true
template: false
phase: 2
duration_weeks: 4
default_output_file: '{output_folder}/JARVIS_PHASE2_BUILD_LOG.md'
