// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using FocusDeck.Persistence;

#nullable disable

namespace FocusDeck.Persistence.Migrations
{
    [DbContext(typeof(AutomationDbContext))]
    [Migration("20251120150000_AddCapturedItemSummaries")]
    partial class AddCapturedItemSummaries
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Stubbed for manual migration creation - we assume the rest of the model is consistent
            // In a real scenario, this would contain the full snapshot
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0");
#pragma warning restore 612, 618
        }
    }
}
