name: Build Mobile App

on:
  push:
    branches: [ master, develop ]
    tags:
      - 'v*'
  pull_request:
    branches: [ master ]

jobs:
  build-android:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build Android Release
      run: dotnet publish src/FocusDeck.Mobile/FocusDeck.Mobile.csproj -f net8.0-android -c Release
    
    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: android-apk
        path: src/FocusDeck.Mobile/bin/Release/net8.0-android/com.focusdeck.*.apk

  release:
    needs: build-android
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: android-apk
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: com.focusdeck.*.apk
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
