name: Build Desktop App

on:
  push:
    branches: [ master, develop ]
    tags:
      - 'v*'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore src/FocusDock.App/FocusDock.App.csproj
    
    - name: Publish WPF Desktop App
      run: dotnet publish src/FocusDock.App/FocusDock.App.csproj -c Release -o ./publish/desktop
    
    - name: Create MSI installer
      run: |
        # Create MSI using WiX (requires WiX Toolset)
        # For now, create a portable ZIP
        Compress-Archive -Path ./publish/desktop/* -DestinationPath FocusDeck-Desktop-${{ github.ref_name }}.zip
      shell: pwsh
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: desktop-build
        path: FocusDeck-Desktop-*.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: desktop-build
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: FocusDeck-Desktop-*.zip
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
